### ISSUE TITLE
persist-indicator: create periods

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/organisationUnit-User-Assigment#14]
Try to find a PeriodGenerator utils class to reuse

**Comment by ivanarrizabalaga** [comment]
An alternative would be to do our own functions based on joda:

https://github.com/js-joda/js-joda/blob/master/CheatSheet.md

**Comment by adrianq** [comment]
@ivanarrizabalaga  Let's use that lib to build an example for monthly and maybe, if it is not too difficult, daily and yearly.

**Comment by adrianq** [comment]
@ivanarrizabalaga  when ready with this. Let me know so I can give it a try in singapore dev server

**Comment by ivanarrizabalaga** [comment]
it looks (http://stackoverflow.com/questions/22716512/joda-time-for-javascript) I should pick up **moment.js** instead of joda (not so popular in js)

**Comment by ivanarrizabalaga** [comment]
@adrianq I've just pushed the periods stuff:

https://github.com/EyeSeeTea/organisationUnit-User-Assigment/tree/script_persist_indicators

**Comment by adrianq** [comment]
Thanks @ivanarrizabalaga! Will test it in dev ([issue](https://github.com/EyeSeeTea/organisationUnit-User-Assigment/issues/21))
