### ISSUE TITLE
outlet-registration: prepare script

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/organisationUnit-User-Assigment#18]

**Comment by ivanarrizabalaga** [comment]
@josemp10, @adrianq 
It looks like some orgunits have children that are not following the same sequence.

I will add a screenshot...

what am I supposed to do here? Only consider AMTR sequence I guess..

**Comment by josemp10** [comment]
Looking into it ....

**Comment by josemp10** [comment]
Ok, I believe the problem is that there are other facilities different to
the AMTR ones (sorry I should have mentioned this)... Yes, you should only
consider the AMTR sequence...
