### ISSUE TITLE
outlet-registration: sync post to avoid autoinc errors

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/organisationUnit-User-Assigment#22]
Orgunits cannot be done in a regular loop since we need to 'post' every new orgunit before trying to resolve the next one.

This is required in order to keep the sequence healthly.

**Comment by ivanarrizabalaga** [comment]
docs to deal with eventEmitters in node:

https://nodejs.org/docs/latest/api/events.html

a basic example:

https://coligo.io/nodejs-event-emitter/

**Comment by josemp10** [comment]
I have applied the following solution

https://mostafa-samir.github.io/async-iterative-patterns-pt1/
