### ISSUE TITLE
Assign a programattribute to an event

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/organisationUnit-User-Assigment#26]

**Comment by adrianq** [comment]
@josemp10 Is this task done? I don't even remember what was it about...

**Comment by adrianq** [comment]
@josemp10 Is this task done? I don't even remember what was it about...

**Comment by josemp10** [comment]
It is not done. It is about assigning program attributes (representing
DHIS2 users) to events (for analytic porpuses). I estimate 15 - 20 hours of
work. It couldn't be done before because of a bug. I can try again the last
week of January

**Comment by josemp10** [comment]
@adrianq  I think we can close this one? I have tested it and everything seemed to be fine. We still have to wait for real cases, but for that we need to wait for PSI - Myanmar. From a dev perspective, I think we can mark this task as done.

**Comment by adrianq** [comment]
Sounds good. Closing the card then
