### ISSUE TITLE
User Program Attribute Assignment script

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/organisationUnit-User-Assigment#34]
- Query all the events with default categoryoption for a particular program in the last 30 days.
...../api/events.json?program=fUycPoiPP58&startDate=2017-01-15&skipPaging=true (Outlet support)
....../api/events.json?program=FcSSx0KtXo9&startDate=2017-01-15&skipPaging=true (BCC)
- For each event get the username, you can get it from the field ‘storedBy’ from the dataValues object
- Then we look for the categoryoption which code is exactly the same as the storedBy value: ..../api/categoryOptions?filter=code:eq:samong
- If the category option does not exist, we iterate to the next Event. 
- If the category option exists, we edit the payload of the event modifying the attributeCategoryOptions to the id of the categoryOptions found (it contained the default categoryoption before). PUT "...../api/events/ [eventId]" Note we need to include all values on the payload. Otherwise, missing values would be imported as blank!!!!

![screenshot from 2017-03-01 10 20 20](https://cloud.githubusercontent.com/assets/6850223/23455777/bd5229e0-fe68-11e6-8e30-6533142e3124.png)

**Comment by adrianq** [comment]
A backup with the database can be found [here](https://drive.google.com/file/d/0B9L0E_5bA3AoMDVYYlN2U3VrRkk/view)  The database needs to be restored using the PgAdming 

It contains these 10 code promoters:
samong
vhawi
nlwin
pei
spkhay
tohlaing
msoe
bmin
skthan
lluthang
winnaing
dztun
zhaung
smmon

**Comment by adrianq** [comment]
@josemp10 We are assuming that if the attributeCategoryOptions is already fulfilled we don't have to perform any action, right? This is important because the script is gonna be executed nightly and therefore we will be iterating over the same events for the last 29 days.

**Comment by tokland** [comment]
PR created: EyeSeeTea/organisationUnit-User-Assigment#36

Some notes:

- I've used ES6 features. Tested against node 6.9.0.
- I've used a different structure for the config.json, for example, the API URL is a single item, and the auth includes user/pass instead of its base64 encoding. This can be changed if needed.
- Added README
- Using package _request-promise_. Works the same than _request_, but returns a promise instead of using a callback function.
- bluebird: Module to run concurrent promises. Not really needed, but it should be faster and it's nice to use.
- Configuration: Beside the json file, the configuration can also be set from the command line if something needs to be customized, see the README for more info.
- Added eslint configuration (see README)

**Comment by tokland** [comment]
To make sure what's being changed, I've diffed the events before and after the processing. Note that the following changes are made automatically by DHIS:

-  lastUpdated in every DataValue is changed. Also, 
- Event lastUpdated updated
- Event attributeOptionCombo is also updated, accordingly with the attributeCategoryOptions.
```
--- json1/XYDPuj0hTA7.json	2017-03-07 11:39:47.634815545 +0100
+++ json2/XYDPuj0hTA7.json	2017-03-07 11:43:35.391150376 +0100
@@ -16,42 +16,42 @@
     },
     "dataValues": [{
         "created": "2016-11-28T03:49:26.370",
-        "lastUpdated": "2016-11-28T03:49:26.370",
+        "lastUpdated": "2017-03-07T11:41:42.045",
         "value": "4",
         "dataElement": "jKhflYb5Vfh",
         "providedElsewhere": false,
         "storedBy": "pei"
     }, {
         "created": "2016-11-28T03:49:26.375",
-        "lastUpdated": "2016-11-28T03:49:26.375",
+        "lastUpdated": "2017-03-07T11:41:42.024",
         "value": "1",
         "dataElement": "jU5ms39fU2K",
         "providedElsewhere": false,
         "storedBy": "pei"
     }, {
         "created": "2016-11-28T03:49:26.380",
-        "lastUpdated": "2016-11-28T03:49:26.380",
+        "lastUpdated": "2017-03-07T11:41:42.032",
         "value": "Thit   To   Kyun",
         "dataElement": "zNpymqMko1h",
         "providedElsewhere": false,
         "storedBy": "pei"
     }, {
         "created": "2016-11-28T03:49:26.354",
-        "lastUpdated": "2016-11-28T03:49:26.354",
+        "lastUpdated": "2017-03-07T11:41:42.074",
         "value": "Ah  Naing   Pun",
         "dataElement": "BOGhfcjLPwV",
         "providedElsewhere": false,
         "storedBy": "pei"
     }, {
         "created": "2016-11-28T03:49:26.364",
-        "lastUpdated": "2016-11-28T03:49:26.364",
+        "lastUpdated": "2017-03-07T11:41:42.099",
         "value": "Pyone Ei (MM-PP)",
         "dataElement": "XHXCyFOeZN6",
         "providedElsewhere": false,
         "storedBy": "pei"
     }, {
         "created": "2016-11-28T03:49:26.359",
-        "lastUpdated": "2016-11-28T03:49:26.359",
+        "lastUpdated": "2017-03-07T11:41:42.114",
         "value": "MM FO - Yangon",
         "dataElement": "IGmOvCQ5qDO",
         "providedElsewhere": false,
@@ -59,9 +59,9 @@
     }],
     "followup": false,
     "created": "2016-11-28T03:49:26.343",
-    "lastUpdated": "2016-11-28T03:49:26.343",
-    "attributeCategoryOptions": "gnS5549wCkG",
-    "attributeOptionCombo": "XfXL6fEveof",
+    "lastUpdated": "2017-03-07T11:41:42.013",
+    "attributeCategoryOptions": "kM5W39mHnvz",
+    "attributeOptionCombo": "UeQUb4q4vAE",
     "completedBy": "pei",
     "completedDate": "2016-11-28T00:00:00.000"
 }
```

Apparently the new attributeCategoryOptions/attributeOptionCombo match fine:

```
dhis2devpsi=# select uid,code,name from dataelementcategoryoption where uid = 'kM5W39mHnvz';
     uid     | code |       name       
-------------+------+------------------
 kM5W39mHnvz | pei  | Pyone Ei (MM-PP)
(1 row)

dhis2devpsi=# select uid,code,name from categoryoptioncombo where uid = 'UeQUb4q4vAE';
     uid     | code |       name       
-------------+------+------------------
 UeQUb4q4vAE |      | Pyone Ei (MM-PP)
(1 row)
```
