### ISSUE TITLE
Active Inactive OU script

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/organisationUnit-User-Assigment#37]
**Input parameters:**
DataElement Group -> Active/Inactive OUs: VZuTpbPy1L9

1. Get All DataElements from Active/Inactive OUs Data Element Group
	..../api/dataElementGroups/VZuTpbPy1L9

1. For each dataElement get its attributes (Level, Org Unit, OrgUnitGroup, n Periods)
..../api/dataElements/gSzTq7WZjqq

   DataElement Attributes
   - Gates - Level (DE): Dci7UEL1fsO
   - Gates - Parent OrgUnit (DE): BF3XnPHZGEM
   - Gates - OrgUnitGroup (DE): IvH9OP1INZu
   - Gates - n Periods (DE): GYVtN5RxY3W

1. Get the periods to check (We will skip this step for now and we will be assuming it is going to be monthly). Get the period of through the dataset (although we are going to use by monthly by default, so we can skip this step)
	...../api/dataSetElements/ALcUnb5qc1e?fields=dataSet[periodType]

1. Once we have the periodType = monthly, we need to include the current periods (months) and the previous n periods. if the n Periods is for example 5, we need to include:

   February 2017 - 201702 - Current month

   January 2017 - 201701
   December 2016 - 201612
   November 2016 - 201611
   October 2016 - 201610
   September 2016 - 201609

1. Get the list of org Units (through the organisationUnit endpoint) based on OrgUnit, Level, OrgUnitGroup
	Get the level of the parent OU .../api/organisationUnits/uAIgQCh8Zvz?fields=level

1. Get the relative level of the OUs

    Gates - Level (DE) - parent OU = 7 - 6=1

1. Get the list of OU  ..../api/organisationUnits/uAIgQCh8Zvz?level=1

1. For each OU get the closedDate.

   If closedDate does not exist then All Periods are Active
   If closedDate is previous than the first period (01/09/2016) and the openingDate is previous than the closedDate then All Periods are Inactive
   In any other case the periods previos than the closedDate (including the same month) are Active and the later periods are Inactive  (unlessl we find an openingDate).

1. API call for Active (we send ‘1’) and Inactive (we send ‘0’)
	End point: ../api/dataValueSets
	Method: POST
	Payload (I recommend to use the same payload for each org. Unit containing all periods)

Example
	Let’s say de closedDate=15/01/2017 then the payload

{
  "dataValues": [
    { "dataElement": "gSzTq7WZjqq", "period": "201609", "orgUnit": "QTKJAo4UBSM", "value": "1" },
    { "dataElement": "gSzTq7WZjqq", "period": "201610", "orgUnit": "QTKJAo4UBSM", "value": "1" },
    { "dataElement": "gSzTq7WZjqq", "period": "201611", "orgUnit": "QTKJAo4UBSM", "value": "1" },
    { "dataElement": "gSzTq7WZjqq", "period": "201612", "orgUnit": "QTKJAo4UBSM", "value": "1" },
    { "dataElement": "gSzTq7WZjqq", "period": "201701", "orgUnit": "QTKJAo4UBSM", "value": "1" },
    { "dataElement": "gSzTq7WZjqq", "period": "201702", "orgUnit": "QTKJAo4UBSM", "value": "0" }
]
}

**Comment by adrianq** [comment]
A backup with the database can be found [here](https://drive.google.com/file/d/0B9L0E_5bA3AoMDVYYlN2U3VrRkk/view)  The database needs to be restored using the PgAdming

**Comment by idelcano** [comment]
hello @josemp10 

I'm having some conflicts  when i try to post the current month period.

Conflict:
```
Values posted OK, summary {
        "responseType": "ImportSummary",
        "status": "SUCCESS",
        "description": "Import process completed successfully",
        "importCount": {
                "imported": 12,
                "updated": 0,
                "ignored": 1,
                "deleted": 0
        },
        "conflicts": [
                {
                        "object": "201703",
                        "value": "Period: 201703 is after latest open future period: 201702 for data element: gSzTq7WZjqq"
                }
        ],
        "dataSetComplete": "false"
}
```


In the first execution of my script, after import the database, is slightly different.

Only in the first execution of my script the server response contains a constraint error for each dataValues, after the first dataValues conflict. 

Constraint error:
```
Values posted OK, summary {
        "responseType": "ImportSummary",
        "status": "ERROR",
        "description": "The import process failed: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [uk_tbkbjga8h4j5u33d7hbcuk66t]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
        "importCount": {
                "imported": 0,
                "updated": 0,
                "ignored": 0,
                "deleted": 0
        }
}
```

Example of dataValues:
```
`"{"dataValues":[{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201603","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201604","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201605","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201606","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201607","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201608","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201609","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201610","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201611","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201612","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201701","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201702","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"**201703**","value":1}]}"`
```

 
But when i try to push each datavalues without the current month, the server response is  successfully:

Example of dataValues:
`"{"dataValues":[{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201603","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201604","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201605","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201606","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201607","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201608","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201609","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201610","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201611","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201612","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201701","value":1},{"dataElement":"gSzTq7WZjqq","orgUnit":"QTKJAo4UBSM","period":"201702","value":1}]}"`

Response:

```
Values posted OK, summary {
        "responseType": "ImportSummary",
        "status": "SUCCESS",
        "description": "Import process completed successfully",
        "importCount": {
                "imported": 12,
                "updated": 0,
                "ignored": 0,
                "deleted": 0
        },
        "dataSetComplete": "false"
}

```
Do you know what should I do?
skip the current month?

Thanks
