### ISSUE TITLE
add insersection behaviour for filters

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/organisationUnit-User-Assigment#6]
Quick filters must be configurable so they can work as the intersection with the current selection.

**Comment by ivanarrizabalaga** [comment]
@adrianq already pushed here:

https://github.com/EyeSeeTea/d2-ui/tree/org_unit_intersection_policy

should I PR? which repo/branch?

**Comment by adrianq** [comment]
Looking good so far. I have made  a couple of minor commits to the app repo and updated the d2-ui with the latest from dhis repo branch v24. I will create specific cards for the things we need to address. @ivanarrizabalaga Let's talk on Thursday about this but basically we need to address these issues before moving to the script thing.
