### ISSUE TITLE
We should only displays user that the logged user is allowed to manage

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/organisationUnit-User-Assigment#63]
We are displaying all users in the dhis2 instance. [The official dhis2 users app also do this](http://dev.eyeseetea.com:8080/dhis-web-maintenance-user/alluser.action) although in my opinion this should be consider as a bug. However we should only display users that can be managed by the current logged user. Api call is /api/users.json?canManage=true, we should perform an equivalent call with d2

**Comment by adrianq** [comment]
@tokland Finally this needs to be implemented. The idea is to add a checkbox at the right side of the search textfield. Something like: 
[] Display only users I can manage

By default, on init, checkbox are disabled, hence all the users are displayed. If checkbox is selected we will filter and display only users that the current logged user can manage. As we discussed we will be using the equivalent to the api call aforementioned in d2.

**Comment by adrianq** [comment]
Btw @tokland you asked me how this concept of user management permissions is defined in Dhis2.

Some information: https://docs.dhis2.org/2.26/en/user/html/ch04s07.html

I have also created a user (user:admin2 pw: same for admin) in dev-est where you can replicate this behaviour in our app

**Comment by troyel** [comment]
Seems to work ! Great!
